export const ARGENTINE_PROVINCES = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Ciudad Autónoma de Buenos Aires",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán"
];

export const ARGENTINE_CITIES = {
  "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "Quilmes", "San Nicolás", "Olavarría", "Otra"],
  "Catamarca": ["San Fernando del Valle de Catamarca", "Belén", "Andalgalá", "Tinogasta", "Santa María", "Otra"],
  "Chaco": ["Resistencia", "Presidencia Roque Sáenz Peña", "Villa Ángela", "Charata", "Otra"],
  "Chubut": ["Comodoro Rivadavia", "Trelew", "Puerto Madryn", "Esquel", "Rawson", "Otra"],
  "Ciudad Autónoma de Buenos Aires": ["CABA", "Otra"],
  "Córdoba": ["Córdoba", "Río Cuarto", "Villa María", "Villa Carlos Paz", "San Francisco", "Alta Gracia", "Otra"],
  "Corrientes": ["Corrientes", "Goya", "Paso de los Libres", "Curuzú Cuatiá", "Mercedes", "Otra"],
  "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Concepción del Uruguay", "Gualeguay", "Otra"],
  "Formosa": ["Formosa", "Clorinda", "Pirané", "El Colorado", "Otra"],
  "Jujuy": ["San Salvador de Jujuy", "San Pedro", "Perico", "Libertador General San Martín", "La Quiaca", "Otra"],
  "La Pampa": ["Santa Rosa", "General Pico", "General Acha", "Eduardo Castex", "Toay", "Otra"],
  "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Chamical", "Chepes", "Otra"],
  "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Guaymallén", "Maipú", "Luján de Cuyo", "Otra"],
  "Misiones": ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú", "Apóstoles", "Otra"],
  "Neuquén": ["Neuquén", "Cutral Có", "Zapala", "Centenario", "Plottier", "San Martín de los Andes", "Otra"],
  "Río Negro": ["San Carlos de Bariloche", "General Roca", "Cipolletti", "Viedma", "Villa Regina", "Otra"],
  "Salta": ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "General Güemes", "Rosario de la Frontera", "Otra"],
  "San Juan": ["San Juan", "Rawson", "Rivadavia", "Chimbas", "Pocito", "Otra"],
  "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "Juana Koslay", "La Punta", "Otra"],
  "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "Pico Truncado", "Las Heras", "Puerto Deseado", "Otra"],
  "Santa Fe": ["Rosario", "Santa Fe", "Rafaela", "Villa Gobernador Gálvez", "Venado Tuerto", "Reconquista", "Otra"],
  "Santiago del Estero": ["Santiago del Estero", "La Banda", "Termas de Río Hondo", "Frías", "Añatuya", "Otra"],
  "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin", "Otra"],
  "Tucumán": ["San Miguel de Tucumán", "Banda del Río Salí", "Yerba Buena", "Tafí Viejo", "Concepción", "Otra"]
};
